[2024-02-26T10:02:05.258-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.create_table_customers manual__2024-02-26T15:02:03.949998+00:00 [queued]>
[2024-02-26T10:02:05.268-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.create_table_customers manual__2024-02-26T15:02:03.949998+00:00 [queued]>
[2024-02-26T10:02:05.268-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-26T10:02:05.275-0500] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_table_customers> on 2024-02-26 15:02:03.949998+00:00
[2024-02-26T10:02:05.277-0500] {standard_task_runner.py:57} INFO - Started process 5654 to run task
[2024-02-26T10:02:05.280-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_pipeline', 'create_table_customers', 'manual__2024-02-26T15:02:03.949998+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/postgres_pipeline.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmpj3grwh4r']
[2024-02-26T10:02:05.282-0500] {standard_task_runner.py:85} INFO - Job 4: Subtask create_table_customers
[2024-02-26T10:02:05.374-0500] {task_command.py:416} INFO - Running <TaskInstance: postgres_pipeline.create_table_customers manual__2024-02-26T15:02:03.949998+00:00 [running]> on host venkatasaismbp.hsd1.nj.comcast.net
[2024-02-26T10:02:05.466-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='create_table_customers' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T15:02:03.949998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T15:02:03.949998+00:00'
[2024-02-26T10:02:05.467-0500] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS customers(
            id INTEGER PRIMARY KEY,
            name VARCHAR(50) NOT NULL
        );
[2024-02-26T10:02:05.486-0500] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2024-02-26T10:02:05.627-0500] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2024-02-26T10:02:05.647-0500] {sql.py:418} INFO - Running statement: CREATE TABLE IF NOT EXISTS customers(
            id INTEGER PRIMARY KEY,
            name VARCHAR(50) NOT NULL
        );, parameters: None
[2024-02-26T10:02:05.656-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(customers, 2200) already exists.

[2024-02-26T10:02:05.671-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_pipeline, task_id=create_table_customers, execution_date=20240226T150203, start_date=20240226T150205, end_date=20240226T150205
[2024-02-26T10:02:05.678-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task create_table_customers (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(customers, 2200) already exists.
; 5654)
[2024-02-26T10:02:05.704-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-26T10:02:05.727-0500] {logging_mixin.py:154} WARNING - /Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/models/baseoperator.py:1203 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-02-26T10:02:05.736-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
